:edit BoardView.js
:tabe /home/cz/drinkwithwater/riddle/static/frontend/src/main.js
:tabe CellView.js
:tabe /home/cz/drinkwithwater/riddle/static/frontend/src/models/CellModel.js
:tabe /home/cz/drinkwithwater/riddle/static/frontend/src/css/global.css
:tabe /home/cz/drinkwithwater/riddle/static/frontend/test.html
:tabe /home/cz/drinkwithwater/riddle/static/frontend/src/templates/cell.html
:tabe /home/cz/drinkwithwater/riddle/static/frontend/src/templates/board.html
:tabn 1
